run_name: klm-utb-4
wandb_project: klm

data_path: data/UltraTextbooks_length
max_seq_length: 65536

epochs: 1
batch_size: 32

learning_rate: 1e-3
weight_decay: 0.001
warmup_steps: 500

output_dir: ./ckpt
log_interval: 5
save_interval: 500

seed: 42
max_grad_norm: 1.0